run:
  timeout: 3m
linters:
  # disable all linters, then enable some specific linters
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gosec
    - stylecheck
    - unconvert

linters-settings:
  staticcheck:
    checks: ["all"]
  stylecheck:
    checks: ["-ST1003"] # ST1003: should not use underscores("_") in Go names
  gosec:
    severity: "low"
    confidence: "low"
    excludes:
      - G101
      - G501
      - G401
      - G107
      - G306
issues:
  exclude-rules:
    - path: _test\.go
      linters: # exclude some linters from running on tests files.
        - errcheck
        - gosec
